### PR TITLE
Skip hostname tests if running under localhost

### PR DESCRIPTION
**Pull request by SKoschnicke**
I think the other tests are also useful when running a test instance of the app under localhost.

### CODE REVIEW

**Comment by jjaffeux** [comment]
@SKoschnicke hi, thx a lot!

Wondering, is this enough ? what if 127.0.0.1 ?

**Comment by ZogStriP** [comment]
What's the point of this? Discourse doctor is for instances running in production. Not development instances

**Comment by jjaffeux** [comment]
And yes I'm also wondering if we should troubleshoot dev instances, or just focus on production.

**Comment by SKoschnicke** [comment]
The hostname could be anything and still be a local test instance, right. But the most logical hostname for that (at least to me) would be `localhost`. 127.0.0.1 is an IP address, not a hostname.

The other tests are also valuable for test instances, but are not performed if the hostname checks fail (which will on an instance not on the public internet). I am not talking about development instances but about staging instances or instances which are run to test a production configuration.

**Comment by SKoschnicke** [comment]
After thinking about it again I came to the conclusion that this is a very special case and should not add complexity to the project. If testing stage servers, one can also just comment the hostname check in the script.

**Comment by jjaffeux** [comment]
@SKoschnicke ok, please feel free to submit any other PR, or discuss it with us on meta, thanks for you contribution anyways.

**Pull request closed without merging**
